// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="u128_to_f32_u128_to_f32,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-fgg484-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.081000,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=341,HLS_SYN_LUT=1195,HLS_VERSION=2023_1}" *)

module u128_to_f32 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r,
        out_r,
        out_r_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] in_r;
output  [31:0] out_r;
output   out_r_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_r_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_subdone;
reg   [127:0] in_r_read_reg_556;
wire    ap_block_pp0_stage0_11001;
reg   [127:0] in_r_read_reg_556_pp0_iter1_reg;
reg   [127:0] in_r_read_reg_556_pp0_iter2_reg;
reg   [127:0] in_r_read_reg_556_pp0_iter3_reg;
reg   [127:0] in_r_read_reg_556_pp0_iter4_reg;
wire   [0:0] icmp_ln79_fu_147_p2;
reg   [0:0] icmp_ln79_reg_562;
reg   [0:0] icmp_ln79_reg_562_pp0_iter1_reg;
wire   [0:0] icmp_ln88_fu_175_p2;
reg   [0:0] icmp_ln88_reg_568;
reg   [0:0] icmp_ln88_reg_568_pp0_iter1_reg;
reg   [15:0] high16_reg_573;
wire   [15:0] trunc_ln101_fu_203_p1;
reg   [15:0] trunc_ln101_reg_579;
wire   [0:0] icmp_ln97_fu_217_p2;
reg   [0:0] icmp_ln97_reg_594;
wire   [0:0] icmp_ln106_fu_238_p2;
reg   [0:0] icmp_ln106_reg_599;
reg   [3:0] high4_reg_604;
reg   [3:0] high4_reg_604_pp0_iter2_reg;
wire   [3:0] trunc_ln119_fu_266_p1;
reg   [3:0] trunc_ln119_reg_610;
reg   [3:0] trunc_ln119_reg_610_pp0_iter2_reg;
wire   [0:0] icmp_ln115_fu_321_p2;
reg   [0:0] icmp_ln115_reg_615;
wire   [7:0] msb_pos_8_fu_332_p3;
reg   [7:0] msb_pos_8_reg_620;
wire   [7:0] msb_pos_12_fu_403_p3;
reg   [7:0] msb_pos_12_reg_626;
reg   [7:0] msb_pos_12_reg_626_pp0_iter4_reg;
wire   [0:0] icmp_ln142_fu_421_p2;
reg   [0:0] icmp_ln142_reg_633;
reg   [0:0] icmp_ln142_reg_633_pp0_iter4_reg;
wire   [31:0] grp_fu_131_p1;
reg   [31:0] conv_reg_638;
wire   [31:0] grp_fu_134_p1;
reg   [31:0] conv1_reg_643;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] grp_fu_131_p0;
wire    ap_block_pp0_stage0;
wire   [63:0] grp_fu_134_p0;
wire   [63:0] high64_fu_137_p4;
wire   [63:0] trunc_ln83_fu_153_p1;
wire   [63:0] select_ln79_fu_157_p3;
wire   [31:0] high32_fu_165_p4;
wire   [31:0] trunc_ln92_fu_181_p1;
wire   [31:0] select_ln88_fu_185_p3;
wire   [15:0] select_ln97_fu_222_p3;
wire   [7:0] high8_fu_228_p4;
wire   [7:0] trunc_ln110_fu_244_p1;
wire   [7:0] select_ln106_fu_248_p3;
wire   [6:0] msb_pos_fu_270_p3;
wire   [6:0] msb_pos_1_fu_277_p3;
wire   [6:0] msb_pos_2_fu_284_p3;
wire   [6:0] msb_pos_3_fu_291_p2;
wire   [6:0] msb_pos_4_fu_297_p3;
wire   [6:0] msb_pos_5_fu_304_p2;
wire   [6:0] msb_pos_6_fu_310_p3;
wire   [7:0] zext_ln72_fu_317_p1;
wire   [7:0] msb_pos_7_fu_326_p2;
wire   [3:0] select_ln115_fu_340_p3;
wire   [1:0] high2_fu_345_p4;
wire   [0:0] icmp_ln124_fu_355_p2;
wire   [7:0] msb_pos_9_fu_361_p2;
wire   [0:0] tmp_fu_373_p3;
wire   [0:0] tmp_2_fu_381_p3;
wire   [7:0] msb_pos_10_fu_366_p3;
wire   [0:0] select_ln124_fu_389_p3;
wire   [7:0] add_ln133_fu_397_p2;
wire   [1:0] tmp_3_fu_411_p4;
wire   [7:0] shift_fu_437_p2;
wire  signed [31:0] sext_ln151_fu_442_p1;
wire   [127:0] zext_ln151_fu_446_p1;
wire   [127:0] lshr_ln151_fu_450_p2;
wire   [30:0] shl_ln_fu_459_p3;
wire   [31:0] zext_ln154_fu_466_p1;
wire   [31:0] add_ln154_fu_470_p2;
wire   [8:0] tmp_1_fu_476_p4;
wire   [22:0] mantissa_fu_455_p1;
wire   [0:0] icmp_ln67_fu_427_p2;
wire   [0:0] icmp_ln140_fu_432_p2;
wire   [0:0] xor_ln67_fu_494_p2;
wire   [0:0] or_ln140_fu_506_p2;
wire   [0:0] xor_ln140_fu_512_p2;
wire   [0:0] and_ln142_fu_518_p2;
wire   [31:0] select_ln142_fu_523_p3;
wire   [0:0] and_ln140_fu_500_p2;
wire   [31:0] result_fu_486_p3;
wire   [0:0] or_ln142_fu_533_p2;
wire   [31:0] bitcast_ln142_fu_529_p1;
wire   [31:0] select_ln142_1_fu_539_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

u128_to_f32_uitofp_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
uitofp_32ns_32_5_no_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_131_p0),
    .ce(1'b1),
    .dout(grp_fu_131_p1)
);

u128_to_f32_uitofp_64ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
uitofp_64ns_32_5_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_134_p0),
    .ce(1'b1),
    .dout(grp_fu_134_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        conv1_reg_643 <= grp_fu_134_p1;
        conv_reg_638 <= grp_fu_131_p1;
        high4_reg_604_pp0_iter2_reg <= high4_reg_604;
        icmp_ln115_reg_615 <= icmp_ln115_fu_321_p2;
        icmp_ln142_reg_633 <= icmp_ln142_fu_421_p2;
        icmp_ln142_reg_633_pp0_iter4_reg <= icmp_ln142_reg_633;
        in_r_read_reg_556_pp0_iter2_reg <= in_r_read_reg_556_pp0_iter1_reg;
        in_r_read_reg_556_pp0_iter3_reg <= in_r_read_reg_556_pp0_iter2_reg;
        in_r_read_reg_556_pp0_iter4_reg <= in_r_read_reg_556_pp0_iter3_reg;
        msb_pos_12_reg_626 <= msb_pos_12_fu_403_p3;
        msb_pos_12_reg_626_pp0_iter4_reg <= msb_pos_12_reg_626;
        msb_pos_8_reg_620[7 : 2] <= msb_pos_8_fu_332_p3[7 : 2];
        trunc_ln119_reg_610_pp0_iter2_reg <= trunc_ln119_reg_610;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        high16_reg_573 <= {{select_ln88_fu_185_p3[31:16]}};
        high4_reg_604 <= {{select_ln106_fu_248_p3[7:4]}};
        icmp_ln106_reg_599 <= icmp_ln106_fu_238_p2;
        icmp_ln79_reg_562 <= icmp_ln79_fu_147_p2;
        icmp_ln79_reg_562_pp0_iter1_reg <= icmp_ln79_reg_562;
        icmp_ln88_reg_568 <= icmp_ln88_fu_175_p2;
        icmp_ln88_reg_568_pp0_iter1_reg <= icmp_ln88_reg_568;
        icmp_ln97_reg_594 <= icmp_ln97_fu_217_p2;
        in_r_read_reg_556 <= in_r;
        in_r_read_reg_556_pp0_iter1_reg <= in_r_read_reg_556;
        trunc_ln101_reg_579 <= trunc_ln101_fu_203_p1;
        trunc_ln119_reg_610 <= trunc_ln119_fu_266_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_r_ap_vld = 1'b1;
    end else begin
        out_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln133_fu_397_p2 = (msb_pos_10_fu_366_p3 + 8'd1);

assign add_ln154_fu_470_p2 = (zext_ln154_fu_466_p1 + 32'd1065353216);

assign and_ln140_fu_500_p2 = (xor_ln67_fu_494_p2 & icmp_ln140_fu_432_p2);

assign and_ln142_fu_518_p2 = (xor_ln140_fu_512_p2 & icmp_ln142_reg_633_pp0_iter4_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign bitcast_ln142_fu_529_p1 = select_ln142_fu_523_p3;

assign grp_fu_131_p0 = in_r[31:0];

assign grp_fu_134_p0 = in_r[63:0];

assign high2_fu_345_p4 = {{select_ln115_fu_340_p3[3:2]}};

assign high32_fu_165_p4 = {{select_ln79_fu_157_p3[63:32]}};

assign high64_fu_137_p4 = {{in_r[127:64]}};

assign high8_fu_228_p4 = {{select_ln97_fu_222_p3[15:8]}};

assign icmp_ln106_fu_238_p2 = ((high8_fu_228_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln115_fu_321_p2 = ((high4_reg_604 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_355_p2 = ((high2_fu_345_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln140_fu_432_p2 = ((msb_pos_12_reg_626_pp0_iter4_reg < 8'd24) ? 1'b1 : 1'b0);

assign icmp_ln142_fu_421_p2 = ((tmp_3_fu_411_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_427_p2 = ((in_r_read_reg_556_pp0_iter4_reg == 128'd0) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_147_p2 = ((high64_fu_137_p4 == 64'd0) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_175_p2 = ((high32_fu_165_p4 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_217_p2 = ((high16_reg_573 == 16'd0) ? 1'b1 : 1'b0);

assign lshr_ln151_fu_450_p2 = in_r_read_reg_556_pp0_iter4_reg >> zext_ln151_fu_446_p1;

assign mantissa_fu_455_p1 = lshr_ln151_fu_450_p2[22:0];

assign msb_pos_10_fu_366_p3 = ((icmp_ln124_fu_355_p2[0:0] == 1'b1) ? msb_pos_8_reg_620 : msb_pos_9_fu_361_p2);

assign msb_pos_12_fu_403_p3 = ((select_ln124_fu_389_p3[0:0] == 1'b1) ? add_ln133_fu_397_p2 : msb_pos_10_fu_366_p3);

assign msb_pos_1_fu_277_p3 = ((icmp_ln79_reg_562_pp0_iter1_reg[0:0] == 1'b1) ? 7'd32 : 7'd96);

assign msb_pos_2_fu_284_p3 = ((icmp_ln88_reg_568_pp0_iter1_reg[0:0] == 1'b1) ? msb_pos_fu_270_p3 : msb_pos_1_fu_277_p3);

assign msb_pos_3_fu_291_p2 = (msb_pos_2_fu_284_p3 | 7'd16);

assign msb_pos_4_fu_297_p3 = ((icmp_ln97_reg_594[0:0] == 1'b1) ? msb_pos_2_fu_284_p3 : msb_pos_3_fu_291_p2);

assign msb_pos_5_fu_304_p2 = (msb_pos_4_fu_297_p3 | 7'd8);

assign msb_pos_6_fu_310_p3 = ((icmp_ln106_reg_599[0:0] == 1'b1) ? msb_pos_4_fu_297_p3 : msb_pos_5_fu_304_p2);

assign msb_pos_7_fu_326_p2 = (zext_ln72_fu_317_p1 + 8'd4);

assign msb_pos_8_fu_332_p3 = ((icmp_ln115_fu_321_p2[0:0] == 1'b1) ? zext_ln72_fu_317_p1 : msb_pos_7_fu_326_p2);

assign msb_pos_9_fu_361_p2 = (msb_pos_8_reg_620 + 8'd2);

assign msb_pos_fu_270_p3 = ((icmp_ln79_reg_562_pp0_iter1_reg[0:0] == 1'b1) ? 7'd0 : 7'd64);

assign or_ln140_fu_506_p2 = (icmp_ln67_fu_427_p2 | icmp_ln140_fu_432_p2);

assign or_ln142_fu_533_p2 = (and_ln142_fu_518_p2 | and_ln140_fu_500_p2);

assign out_r = ((or_ln142_fu_533_p2[0:0] == 1'b1) ? bitcast_ln142_fu_529_p1 : select_ln142_1_fu_539_p3);

assign result_fu_486_p3 = {{tmp_1_fu_476_p4}, {mantissa_fu_455_p1}};

assign select_ln106_fu_248_p3 = ((icmp_ln106_fu_238_p2[0:0] == 1'b1) ? trunc_ln110_fu_244_p1 : high8_fu_228_p4);

assign select_ln115_fu_340_p3 = ((icmp_ln115_reg_615[0:0] == 1'b1) ? trunc_ln119_reg_610_pp0_iter2_reg : high4_reg_604_pp0_iter2_reg);

assign select_ln124_fu_389_p3 = ((icmp_ln124_fu_355_p2[0:0] == 1'b1) ? tmp_fu_373_p3 : tmp_2_fu_381_p3);

assign select_ln142_1_fu_539_p3 = ((icmp_ln67_fu_427_p2[0:0] == 1'b1) ? 32'd0 : result_fu_486_p3);

assign select_ln142_fu_523_p3 = ((and_ln142_fu_518_p2[0:0] == 1'b1) ? conv1_reg_643 : conv_reg_638);

assign select_ln79_fu_157_p3 = ((icmp_ln79_fu_147_p2[0:0] == 1'b1) ? trunc_ln83_fu_153_p1 : high64_fu_137_p4);

assign select_ln88_fu_185_p3 = ((icmp_ln88_fu_175_p2[0:0] == 1'b1) ? trunc_ln92_fu_181_p1 : high32_fu_165_p4);

assign select_ln97_fu_222_p3 = ((icmp_ln97_fu_217_p2[0:0] == 1'b1) ? trunc_ln101_reg_579 : high16_reg_573);

assign sext_ln151_fu_442_p1 = $signed(shift_fu_437_p2);

assign shift_fu_437_p2 = ($signed(msb_pos_12_reg_626_pp0_iter4_reg) + $signed(8'd233));

assign shl_ln_fu_459_p3 = {{msb_pos_12_reg_626_pp0_iter4_reg}, {23'd0}};

assign tmp_1_fu_476_p4 = {{add_ln154_fu_470_p2[31:23]}};

assign tmp_2_fu_381_p3 = select_ln115_fu_340_p3[32'd3];

assign tmp_3_fu_411_p4 = {{msb_pos_12_fu_403_p3[7:6]}};

assign tmp_fu_373_p3 = select_ln115_fu_340_p3[32'd1];

assign trunc_ln101_fu_203_p1 = select_ln88_fu_185_p3[15:0];

assign trunc_ln110_fu_244_p1 = select_ln97_fu_222_p3[7:0];

assign trunc_ln119_fu_266_p1 = select_ln106_fu_248_p3[3:0];

assign trunc_ln83_fu_153_p1 = in_r[63:0];

assign trunc_ln92_fu_181_p1 = select_ln79_fu_157_p3[31:0];

assign xor_ln140_fu_512_p2 = (or_ln140_fu_506_p2 ^ 1'd1);

assign xor_ln67_fu_494_p2 = (icmp_ln67_fu_427_p2 ^ 1'd1);

assign zext_ln151_fu_446_p1 = $unsigned(sext_ln151_fu_442_p1);

assign zext_ln154_fu_466_p1 = shl_ln_fu_459_p3;

assign zext_ln72_fu_317_p1 = msb_pos_6_fu_310_p3;

always @ (posedge ap_clk) begin
    msb_pos_8_reg_620[1:0] <= 2'b00;
end

endmodule //u128_to_f32
