-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity u128_to_f32 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_r : IN STD_LOGIC_VECTOR (127 downto 0);
    out_r : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_ap_vld : OUT STD_LOGIC );
end;


architecture behav of u128_to_f32 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "u128_to_f32_u128_to_f32,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-fgg484-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.081000,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=341,HLS_SYN_LUT=1195,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_20 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_const_lv7_60 : STD_LOGIC_VECTOR (6 downto 0) := "1100000";
    constant ap_const_lv7_10 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_18 : STD_LOGIC_VECTOR (7 downto 0) := "00011000";
    constant ap_const_lv8_E9 : STD_LOGIC_VECTOR (7 downto 0) := "11101001";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal in_r_read_reg_556 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal in_r_read_reg_556_pp0_iter1_reg : STD_LOGIC_VECTOR (127 downto 0);
    signal in_r_read_reg_556_pp0_iter2_reg : STD_LOGIC_VECTOR (127 downto 0);
    signal in_r_read_reg_556_pp0_iter3_reg : STD_LOGIC_VECTOR (127 downto 0);
    signal in_r_read_reg_556_pp0_iter4_reg : STD_LOGIC_VECTOR (127 downto 0);
    signal icmp_ln79_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_562 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_562_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_fu_175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_568 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_568_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal high16_reg_573 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln101_fu_203_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln101_reg_579 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln97_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln97_reg_594 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_reg_599 : STD_LOGIC_VECTOR (0 downto 0);
    signal high4_reg_604 : STD_LOGIC_VECTOR (3 downto 0);
    signal high4_reg_604_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln119_fu_266_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln119_reg_610 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln119_reg_610_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln115_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_reg_615 : STD_LOGIC_VECTOR (0 downto 0);
    signal msb_pos_8_fu_332_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal msb_pos_8_reg_620 : STD_LOGIC_VECTOR (7 downto 0);
    signal msb_pos_12_fu_403_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal msb_pos_12_reg_626 : STD_LOGIC_VECTOR (7 downto 0);
    signal msb_pos_12_reg_626_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln142_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln142_reg_633 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln142_reg_633_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_131_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_reg_638 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_134_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_reg_643 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_131_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_fu_134_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal high64_fu_137_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln83_fu_153_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln79_fu_157_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal high32_fu_165_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln92_fu_181_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln88_fu_185_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln97_fu_222_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal high8_fu_228_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln110_fu_244_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln106_fu_248_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal msb_pos_fu_270_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal msb_pos_1_fu_277_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal msb_pos_2_fu_284_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal msb_pos_3_fu_291_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal msb_pos_4_fu_297_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal msb_pos_5_fu_304_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal msb_pos_6_fu_310_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln72_fu_317_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal msb_pos_7_fu_326_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln115_fu_340_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal high2_fu_345_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln124_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal msb_pos_9_fu_361_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_373_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_381_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal msb_pos_10_fu_366_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln124_fu_389_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln133_fu_397_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_411_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal shift_fu_437_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln151_fu_442_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln151_fu_446_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal lshr_ln151_fu_450_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal shl_ln_fu_459_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln154_fu_466_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln154_fu_470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_476_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal mantissa_fu_455_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln67_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln140_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln67_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln140_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln140_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln142_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln142_fu_523_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln140_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_fu_486_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln142_fu_533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln142_fu_529_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln142_1_fu_539_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to4 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component u128_to_f32_uitofp_32ns_32_5_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component u128_to_f32_uitofp_64ns_32_5_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    uitofp_32ns_32_5_no_dsp_1_U1 : component u128_to_f32_uitofp_32ns_32_5_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_131_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_131_p1);

    uitofp_64ns_32_5_no_dsp_1_U2 : component u128_to_f32_uitofp_64ns_32_5_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_134_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_134_p1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                conv1_reg_643 <= grp_fu_134_p1;
                conv_reg_638 <= grp_fu_131_p1;
                high4_reg_604_pp0_iter2_reg <= high4_reg_604;
                icmp_ln115_reg_615 <= icmp_ln115_fu_321_p2;
                icmp_ln142_reg_633 <= icmp_ln142_fu_421_p2;
                icmp_ln142_reg_633_pp0_iter4_reg <= icmp_ln142_reg_633;
                in_r_read_reg_556_pp0_iter2_reg <= in_r_read_reg_556_pp0_iter1_reg;
                in_r_read_reg_556_pp0_iter3_reg <= in_r_read_reg_556_pp0_iter2_reg;
                in_r_read_reg_556_pp0_iter4_reg <= in_r_read_reg_556_pp0_iter3_reg;
                msb_pos_12_reg_626 <= msb_pos_12_fu_403_p3;
                msb_pos_12_reg_626_pp0_iter4_reg <= msb_pos_12_reg_626;
                    msb_pos_8_reg_620(7 downto 2) <= msb_pos_8_fu_332_p3(7 downto 2);
                trunc_ln119_reg_610_pp0_iter2_reg <= trunc_ln119_reg_610;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                high16_reg_573 <= select_ln88_fu_185_p3(31 downto 16);
                high4_reg_604 <= select_ln106_fu_248_p3(7 downto 4);
                icmp_ln106_reg_599 <= icmp_ln106_fu_238_p2;
                icmp_ln79_reg_562 <= icmp_ln79_fu_147_p2;
                icmp_ln79_reg_562_pp0_iter1_reg <= icmp_ln79_reg_562;
                icmp_ln88_reg_568 <= icmp_ln88_fu_175_p2;
                icmp_ln88_reg_568_pp0_iter1_reg <= icmp_ln88_reg_568;
                icmp_ln97_reg_594 <= icmp_ln97_fu_217_p2;
                in_r_read_reg_556 <= in_r;
                in_r_read_reg_556_pp0_iter1_reg <= in_r_read_reg_556;
                trunc_ln101_reg_579 <= trunc_ln101_fu_203_p1;
                trunc_ln119_reg_610 <= trunc_ln119_fu_266_p1;
            end if;
        end if;
    end process;
    msb_pos_8_reg_620(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln133_fu_397_p2 <= std_logic_vector(unsigned(msb_pos_10_fu_366_p3) + unsigned(ap_const_lv8_1));
    add_ln154_fu_470_p2 <= std_logic_vector(unsigned(zext_ln154_fu_466_p1) + unsigned(ap_const_lv32_3F800000));
    and_ln140_fu_500_p2 <= (xor_ln67_fu_494_p2 and icmp_ln140_fu_432_p2);
    and_ln142_fu_518_p2 <= (xor_ln140_fu_512_p2 and icmp_ln142_reg_633_pp0_iter4_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to4)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to4 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln142_fu_529_p1 <= select_ln142_fu_523_p3;
    grp_fu_131_p0 <= in_r(32 - 1 downto 0);
    grp_fu_134_p0 <= in_r(64 - 1 downto 0);
    high2_fu_345_p4 <= select_ln115_fu_340_p3(3 downto 2);
    high32_fu_165_p4 <= select_ln79_fu_157_p3(63 downto 32);
    high64_fu_137_p4 <= in_r(127 downto 64);
    high8_fu_228_p4 <= select_ln97_fu_222_p3(15 downto 8);
    icmp_ln106_fu_238_p2 <= "1" when (high8_fu_228_p4 = ap_const_lv8_0) else "0";
    icmp_ln115_fu_321_p2 <= "1" when (high4_reg_604 = ap_const_lv4_0) else "0";
    icmp_ln124_fu_355_p2 <= "1" when (high2_fu_345_p4 = ap_const_lv2_0) else "0";
    icmp_ln140_fu_432_p2 <= "1" when (unsigned(msb_pos_12_reg_626_pp0_iter4_reg) < unsigned(ap_const_lv8_18)) else "0";
    icmp_ln142_fu_421_p2 <= "1" when (tmp_3_fu_411_p4 = ap_const_lv2_0) else "0";
    icmp_ln67_fu_427_p2 <= "1" when (in_r_read_reg_556_pp0_iter4_reg = ap_const_lv128_lc_1) else "0";
    icmp_ln79_fu_147_p2 <= "1" when (high64_fu_137_p4 = ap_const_lv64_0) else "0";
    icmp_ln88_fu_175_p2 <= "1" when (high32_fu_165_p4 = ap_const_lv32_0) else "0";
    icmp_ln97_fu_217_p2 <= "1" when (high16_reg_573 = ap_const_lv16_0) else "0";
    lshr_ln151_fu_450_p2 <= std_logic_vector(shift_right(unsigned(in_r_read_reg_556_pp0_iter4_reg),to_integer(unsigned('0' & zext_ln151_fu_446_p1(31-1 downto 0)))));
    mantissa_fu_455_p1 <= lshr_ln151_fu_450_p2(23 - 1 downto 0);
    msb_pos_10_fu_366_p3 <= 
        msb_pos_8_reg_620 when (icmp_ln124_fu_355_p2(0) = '1') else 
        msb_pos_9_fu_361_p2;
    msb_pos_12_fu_403_p3 <= 
        add_ln133_fu_397_p2 when (select_ln124_fu_389_p3(0) = '1') else 
        msb_pos_10_fu_366_p3;
    msb_pos_1_fu_277_p3 <= 
        ap_const_lv7_20 when (icmp_ln79_reg_562_pp0_iter1_reg(0) = '1') else 
        ap_const_lv7_60;
    msb_pos_2_fu_284_p3 <= 
        msb_pos_fu_270_p3 when (icmp_ln88_reg_568_pp0_iter1_reg(0) = '1') else 
        msb_pos_1_fu_277_p3;
    msb_pos_3_fu_291_p2 <= (msb_pos_2_fu_284_p3 or ap_const_lv7_10);
    msb_pos_4_fu_297_p3 <= 
        msb_pos_2_fu_284_p3 when (icmp_ln97_reg_594(0) = '1') else 
        msb_pos_3_fu_291_p2;
    msb_pos_5_fu_304_p2 <= (msb_pos_4_fu_297_p3 or ap_const_lv7_8);
    msb_pos_6_fu_310_p3 <= 
        msb_pos_4_fu_297_p3 when (icmp_ln106_reg_599(0) = '1') else 
        msb_pos_5_fu_304_p2;
    msb_pos_7_fu_326_p2 <= std_logic_vector(unsigned(zext_ln72_fu_317_p1) + unsigned(ap_const_lv8_4));
    msb_pos_8_fu_332_p3 <= 
        zext_ln72_fu_317_p1 when (icmp_ln115_fu_321_p2(0) = '1') else 
        msb_pos_7_fu_326_p2;
    msb_pos_9_fu_361_p2 <= std_logic_vector(unsigned(msb_pos_8_reg_620) + unsigned(ap_const_lv8_2));
    msb_pos_fu_270_p3 <= 
        ap_const_lv7_0 when (icmp_ln79_reg_562_pp0_iter1_reg(0) = '1') else 
        ap_const_lv7_40;
    or_ln140_fu_506_p2 <= (icmp_ln67_fu_427_p2 or icmp_ln140_fu_432_p2);
    or_ln142_fu_533_p2 <= (and_ln142_fu_518_p2 or and_ln140_fu_500_p2);
    out_r <= 
        bitcast_ln142_fu_529_p1 when (or_ln142_fu_533_p2(0) = '1') else 
        select_ln142_1_fu_539_p3;

    out_r_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            out_r_ap_vld <= ap_const_logic_1;
        else 
            out_r_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    result_fu_486_p3 <= (tmp_1_fu_476_p4 & mantissa_fu_455_p1);
    select_ln106_fu_248_p3 <= 
        trunc_ln110_fu_244_p1 when (icmp_ln106_fu_238_p2(0) = '1') else 
        high8_fu_228_p4;
    select_ln115_fu_340_p3 <= 
        trunc_ln119_reg_610_pp0_iter2_reg when (icmp_ln115_reg_615(0) = '1') else 
        high4_reg_604_pp0_iter2_reg;
    select_ln124_fu_389_p3 <= 
        tmp_fu_373_p3 when (icmp_ln124_fu_355_p2(0) = '1') else 
        tmp_2_fu_381_p3;
    select_ln142_1_fu_539_p3 <= 
        ap_const_lv32_0 when (icmp_ln67_fu_427_p2(0) = '1') else 
        result_fu_486_p3;
    select_ln142_fu_523_p3 <= 
        conv1_reg_643 when (and_ln142_fu_518_p2(0) = '1') else 
        conv_reg_638;
    select_ln79_fu_157_p3 <= 
        trunc_ln83_fu_153_p1 when (icmp_ln79_fu_147_p2(0) = '1') else 
        high64_fu_137_p4;
    select_ln88_fu_185_p3 <= 
        trunc_ln92_fu_181_p1 when (icmp_ln88_fu_175_p2(0) = '1') else 
        high32_fu_165_p4;
    select_ln97_fu_222_p3 <= 
        trunc_ln101_reg_579 when (icmp_ln97_fu_217_p2(0) = '1') else 
        high16_reg_573;
        sext_ln151_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shift_fu_437_p2),32));

    shift_fu_437_p2 <= std_logic_vector(unsigned(msb_pos_12_reg_626_pp0_iter4_reg) + unsigned(ap_const_lv8_E9));
    shl_ln_fu_459_p3 <= (msb_pos_12_reg_626_pp0_iter4_reg & ap_const_lv23_0);
    tmp_1_fu_476_p4 <= add_ln154_fu_470_p2(31 downto 23);
    tmp_2_fu_381_p3 <= select_ln115_fu_340_p3(3 downto 3);
    tmp_3_fu_411_p4 <= msb_pos_12_fu_403_p3(7 downto 6);
    tmp_fu_373_p3 <= select_ln115_fu_340_p3(1 downto 1);
    trunc_ln101_fu_203_p1 <= select_ln88_fu_185_p3(16 - 1 downto 0);
    trunc_ln110_fu_244_p1 <= select_ln97_fu_222_p3(8 - 1 downto 0);
    trunc_ln119_fu_266_p1 <= select_ln106_fu_248_p3(4 - 1 downto 0);
    trunc_ln83_fu_153_p1 <= in_r(64 - 1 downto 0);
    trunc_ln92_fu_181_p1 <= select_ln79_fu_157_p3(32 - 1 downto 0);
    xor_ln140_fu_512_p2 <= (or_ln140_fu_506_p2 xor ap_const_lv1_1);
    xor_ln67_fu_494_p2 <= (icmp_ln67_fu_427_p2 xor ap_const_lv1_1);
    zext_ln151_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln151_fu_442_p1),128));
    zext_ln154_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_459_p3),32));
    zext_ln72_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(msb_pos_6_fu_310_p3),8));
end behav;
